version: '3.1'

services:
  app:
    image: 'parking-control-api:latest'
    build:
      context: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/parking-control-db
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: "parking-control-db"
    ports:
      - "5432:5432"